#!/usr/bin/perl
use strict;
use FindBin qw($RealBin);
use IO::Compress::Zip qw(zip $ZipError);

my $xpi_file = 'stash.xpi';
unlink($xpi_file) if -e $xpi_file;
zip [qw( bootstrap.js README.md install.rdf LICENSE.txt )] => $xpi_file
    or die "zip failed: $ZipError\n";
